import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";
import "@/globalStyles/globals.css";
import "@/globalStyles/normalize.css";

const inter = Inter({ subsets: ["latin"] });
const fira = Fira_Code({
	subsets: ["greek"],
	weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body className={fira.className}>{children}</body>
		</html>
	);
}
